version: '3.8'

services:
  backend:
    build: ./backend
    # image: 043309345655.dkr.ecr.ap-northeast-1.amazonaws.com/todo:backend-latest # コンテナイメージをECRから取得するように設定
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/todo
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      args:
        VITE_LOCAL_API_HOST: ${VITE_LOCAL_API_HOST}
        VITE_LOCAL_API_PATH: ${VITE_LOCAL_API_PATH}
    env_file:
      - .env
    # image: 043309345655.dkr.ecr.ap-northeast-1.amazonaws.com/todo:frontend-latest
    ports:
      - "3000:80"

    depends_on:
      - backend

  db:
    image: mysql:8
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_DATABASE: todo
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
